# Generated by Django 2.0.13 on 2019-11-24 15:49

from django.db import migrations, models
import django.db.models.deletion
import student_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_data', models.ImageField(null=True, upload_to=student_info.models.FaceImages.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='faceimages',
            name='student_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_info.Student'),
        ),
    ]
