# Generated by Django 2.2.7 on 2019-12-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=20)),
                ('student_email', models.EmailField(default='student@email.com', max_length=50, null=True, unique=True)),
                ('student_video_data', models.FileField(null=True, upload_to='students/video')),
            ],
        ),
        migrations.CreateModel(
            name='StudentImagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.FileField(upload_to='students/images')),
                ('image_name', models.CharField(max_length=20, null=True)),
                ('image_date_upload', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_info.Student')),
            ],
        ),
    ]
