# Generated by Django 2.2.7 on 2019-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(max_length=20)),
                ('teacher_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('teacher_image', models.ImageField(null=True, upload_to='teachers/images')),
                ('teacher_name', models.CharField(max_length=20)),
            ],
        ),
    ]
